server {
  listen 80;
  server_name _;

  location /api/ {
    proxy_pass http://backend:3001/api/;
  }

  location /media/ {
    proxy_pass http://backend:3001/media/;
  }

  location / {
    root /usr/share/nginx/html;
    try_files $uri $uri/ /index.html;
  }
}
